image: node:8.11.3-jessie

stages: 
  - production

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

production:
  stage: production
  script:
    - npm install
    - npm run build
    - cd dist
    - ssh ubuntu@treyfoster.com -o StrictHostKeyChecking=no
    - scp -r . ubuntu@treyfoster.com:/home/ubuntu/apps/raft.treyfoster.com/
